export const strings = {
    app_name: 'Swordfall Adventure',
    title_character: 'Character',
    title_inventory: 'Inventory',
    title_adventure: 'Adventure',
    title_town: 'Town',
    title_settings: 'Settings',
    quest_rewards: 'Rewards',
    value_empty: '-',
    notification_channel_id: 'notifications_1515',
    equipment: 'Equipment',
    physical_atk: 'Physical ATK',
    physical_res: 'Physical RES',
    magical_atk: 'Magical ATK',
    magical_res: 'Magical RES',
    critical: 'Critical',
    dodge: 'Dodge',
    health: 'Health',
    basic_attack: 'Basic Attack',
    spells: 'Spells',
    buffs: 'Buffs',
    leave_combat: 'Leave Combat',
    flee: 'Flee',
    attack: 'Attack',
    equipped_item: 'Equipped Item',
    upgrade: 'Upgrade',
    unequip: 'Unequip',
    plus: '+',
    equip: 'Equip',
    Break: 'Break',
    discard: 'Discard',
    equipped: 'Equipped',
    hunting_zones: 'Hunting Zones',
    back: 'Back',
    go_deeper: 'Go Deeper',
    reset: 'Reset',
    rewards: 'Rewards',
    xp: 'XP',
    no_items_received: 'No items received.',
    gathering_zones: 'Gathering Zones',
    explore: 'Explore',
    gather: 'Gather',
    mountains: 'Mountains',
    forest: 'Forest',
    claim: 'Claim',
    open: 'Open',
    use: 'Use',
    crafting_table: 'Crafting Table',
    consumables: 'Consumables',
    resources: 'Resources',
    craft: 'Craft',
    materials: 'Materials',
    next_enh: 'Next Enh.',
    crafting: 'Crafting',
    offense: 'Offense',
    defense: 'Defense',
    next_rank: 'Next Rank',
    apply: 'Apply',
    available_points: 'Available Points:',
    cooldown: 'Cooldown:',
    active_spells: 'Active Spells',
    active_buffs: 'Active Buffs',
    yes: 'Yes',
    no: 'No',
    convert: 'Convert',
    depth_bonus: 'Depth Bonus',
    swampland: 'Swampland',
    missions_refresh_in: 'Missions refresh in:',
    rewards_label: 'Rewards:',
    start: 'Start',
    strength: 'Strength',
    dexterity: 'Dexterity',
    intelligence: 'Intelligence',
    charisma: 'Charisma',
    exploring_level: 'Exploring Level',
};
